### ISSUE TITLE
numpy.lstsq seems return wrong rank

### ISSUE THREAD

**Issue by jc5201** [JunyiZhu-AI/R-GAP#2]
Hi.
I found something weird with your code.
np.linalg.lstsq() returns rank of A with result, but it seems not correct.
I compared it with torch.matrix_rank() and two functions returned different rank.
I can't convince which is correct, but I think it is worth checking.

**Comment by JunyiZhu-AI** [comment]
Hi,
This is also an issue related to the numerical error. Both np.linalg.lstsq() and torch.matrix_rank() are using SVD to compute the matrix rank. So the result depends on the cut-off ratio and other factors. Please refer to the description of 'rcond' of the [np.linalg.lstsq()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html)  for more information.
